from pandas import Series, DataFrame
import pandas as pd

def load_co2highlights():
	
	''' 
	Load data tables from the freely available IEA CO2 Highlights 
	dataset, which is made available by the International Energy Agency
	at: https://www.iea.org/media/statistics/CO2Highlights.xls

	This function returns a dictionary of DataFrames, one table per 
	variable, for the following variables:

	   - Population
	   - Total Primary Energy Supply (TPES) in TWh
	   - Total Primary Energy Supply (TPES) in kWh
	   - Total Primary Energy Supply (TPES) in kWh per person

	The DataFrames in turn contain timeseries for a number of countries.
	'''
	
	# Source: https://www.iea.org/media/statistics/CO2Highlights.xls
	file_ieaco2_2016 = pd.ExcelFile('CO2Highlights.xls')

	table_ieapop = file_ieaco2_2016.parse('POP', header=1, skiprows=2, na_values='..').set_index('millions').drop(['Region/Country/Economy']).convert_objects(convert_numeric=True)
	table_ieatpes = file_ieaco2_2016.parse('TPES Mtoe', header=1, skiprows=2, na_values='..').set_index('million tonnes of oil equivalent').drop(['Region/Country/Economy']).convert_objects(convert_numeric=True)

	kWh_per_Mtoe = 11630000000
	TWh_per_Mtoe = 11.6300000

	table_ieapop.index = table_ieapop.index.str.strip()
	table_ieatpes.index = table_ieatpes.index.str.strip()

	pop = table_ieapop * 1e6
	tpes_kwh = table_ieatpes * kWh_per_Mtoe
	tpes_twh = table_ieatpes * TWh_per_Mtoe
	tpes_kwh_person = tpes_kwh / pop

	tables = {'population': pop, 'TPES_kWh': tpes_kwh, 'TPES_TWh': tpes_twh, 'TPES_KWh_per_person': tpes_kwh_person}

	return tables

def select_year (tables, year):

	''' 
	This function takes as input the dictionary of DataFrames
	generated by load_co2highlights(), and outputs a new dictionary
	with country-data for a given year, for the following variables:

	   - Population
	   - Total Primary Energy Supply (TPES) in TWh
	   - Total Primary Energy Supply (TPES) in kWh
	   - Total Primary Energy Supply (TPES) in kWh per person
	   - Total Primary Energy Supply (TPES) in TWh per day
	   - Total Primary Energy Supply (TPES) in kWh per day
	   - Total Primary Energy Supply (TPES) in kWh per person per day
	'''

	import calendar
	days = 366 if calendar.isleap(year) else 365

	pop = tables['population']
	tpes_twh = tables['TPES_TWh']
	tpes_kwh = tables['TPES_kWh']
	tpes_kwh_person = tables['TPES_KWh_per_person']
	
	pop = pop[:][year].dropna()
	tpes_twh = tpes_twh[:][year].dropna()
	tpes_twh_day = tpes_twh / days
	tpes_kwh = tpes_kwh[:][year].dropna()
	tpes_kwh_day = tpes_kwh / days
	tpes_kwh_person = tpes_kwh_person[:][year].dropna()
	tpes_kwh_person_day = tpes_kwh_person / days
	
	tables = {'population': pop, 'TPES_kWh': tpes_kwh, 'TPES_TWh': tpes_twh, 'TPES_KWh_per_person': tpes_kwh_person, 'TPES_kWh_per_day': tpes_kwh_day, 'TPES_TWh_per_day': tpes_twh_day, 'TPES_KWh_per_person_per_day': tpes_kwh_person_day}

	return tables

